### PR TITLE
Correct formatting error

### PR DESCRIPTION
**Pull request by ksbhaskar**
Formatting of documentation for ydb_eintr_handler() was garbled as a Markdown construct was used in a ReStructured text file. Corrected.

### CODE REVIEW

**Comment by ksbhaskar** [comment]
@berwynhoyt Please review and approve. Thanks.

**Comment by berwynhoyt** [comment]
@ksbhaskar Ah. Here on github is the docs change you requested: that's why I couldn't find it on Gitlab!

**Comment by berwynhoyt** [comment]
> Formatting of documentation for ydb_eintr_handler() was garbled as a Markdown construct was used in a ReStructured text file. Corrected.

Thanks for finding this issue, @ksbhaskar. However, you have edited a generated file (generated by `make docs`). The actual source of the problem was in a doc-comment within `yottadb.lua` which had a surplus (and therefore unmatched) backquote. The problem was not that a Markdown construct was used. I have removed the surplus backquote and regenerated the docs, which should fix the problem.

Note that the Markdown in `yottadb.lua` (a single backquote) is converted to valid RestructuredText (a double backquote) by a Lua script that is part of the docs generator.

As for your preferred used of `:code:`, that is more difficult. The double-backquote has been used instead, throughout the lua-yottadb docs and does not appear to cause RestructuredText problems. If you wished to changed this to `:code:` throughout the docs, the correct way to do so would be to alter the Lua script `docs/config/ydb/ldoc.ltp` which converts Markdown into RestructuredText. Currently that script can get away with the simple gsub on line 31, replacing single-backquotes with double-backquotes. If it were to use `:code:` then it would have to figure out whether each backquote were an opening or closing backquote. Do you wish me to spend time on this?

**Comment by ksbhaskar** [comment]
@berwynhoyt Is there anything I need to do other than close the Pull Request? Thanks.

**Comment by berwynhoyt** [comment]
> @berwynhoyt Is there anything I need to do other than close the Pull Request? Thanks.

Other than merge the PR? No. And since I have just hit Merge, you should have nothing further to do.

**Comment by ksbhaskar** [comment]
Thanks @berwynhoyt

**Pull request merged**
